# Generated by Django 3.2.3 on 2021-08-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='myaccount',
        ),
    ]
